import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'


const inter = Outfit({ subsets: ['latin'] })
{/*Bu satır, next/font/google paketinden Inter ve Outfit adlı font türlerini içeri aktarır. 
Bu, özel bir fontun uygulamada kullanılmasını sağlar. 
Uygulamanın başlık ve açıklama bilgilerini içeren metadata nesnesi ↓↓
*/}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  )
}
